### ISSUE TITLE
Measure blood pressure

### ISSUE THREAD

**Issue by wilfredonoyola** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#13]
Hi All,

I have researched about measure blood pressure, I have talked with some Doctors about it.

On overview the doctors say this:
From the electrocardiogram it is possible to calculate many important values, this includes blood pressure. 

From your experience you know some project, document or research that I can follow to calculate blood pressure.

Thanks for your time.

**Comment by joelSensor** [comment]
Hi Wilfredo,

Thanks for reaching out.
Please know that our Pulse Sensor is not intended for medical use.
That said, the only method that I know of for deriving blood pressure from ECG and/or PPG (Pulse Sensor is a PPG) is by measuring something called Pulse Transit Time. I recommend that you do a google search for Pulse Transit Time, and you will come up with many scholarly articles.

**Comment by wilfredonoyola** [comment]
Thanks for you reply,

I will try with Pulse Transit time :)

**Comment by biomurph** [comment]
Just want to let you know that we have posted code that will measure PPT from two Pulse Sensors! Find it here
https://pulsesensor.com/pages/pulse-transit-time
