### ISSUE TITLE
Could not parse -1 for --display

### ISSUE THREAD

**Issue by mrdela** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#21]
I have a problem zu start the process.

Could not parse -1 for --display
/dev/cu.AirPodsvonSebastian-Wir-1 /dev/cu.Bluetooth-Incoming-Port /dev/cu.usbmodemFA121 /dev/tty.AirPodsvonSebastian-Wir-1 /dev/tty.Bluetooth-Incoming-Port /dev/tty.usbmodemFA121

**Comment by mrdela** [comment]
Ok it solved

**Comment by biomurph** [comment]
Great!
