### ISSUE TITLE
I got alphabetical numeral after output to Processing_visualizer, is this ascii? and how do i convert it back to string using processing?

### ISSUE THREAD

**Issue by qkaifong** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#24]
![ascii](https://user-images.githubusercontent.com/51949326/59667031-9fbe4d80-91e8-11e9-9445-9a3cf680c48d.png)
Hi, im doing a school project and want to capture the pulse waveform value into an excel sheet. But when converted to processing_visualizer in arduino, the values i captured are alphabetical numeral and if this is ascii or dec value, how do i convert back to the pulse waveform value in processing? Thank you

**Comment by qkaifong** [comment]
Here's what i captured in excel:
![excel](https://user-images.githubusercontent.com/51949326/59667495-6b975c80-91e9-11e9-95c5-319a0de5d481.png)

**Comment by biomurph** [comment]
@qkaifong 
 The way that the Processing Visualizer formats the data is to be used with our Processing sketches.
It looks like you are trying to use more than one Pulse Sensor. Is that correct?

If you just want the data, you will need to either set the OUTPUT_TYPE as SERIAL_PLOTTER, or remove the ascii letter at the begining of the data points yourself.

We're working on an OUTPUT_TYPE that will output raw data, and be easier to save and store on a computer.

**Comment by qkaifong** [comment]
> It looks like you are trying to use more than one Pulse Sensor. Is that correct?

Yes!

> If you just want the data, you will need to either set the OUTPUT_TYPE as SERIAL_PLOTTER

I'm creating a GUI in processing, so i will need my Output_type to be processing_visualize. 
 
> or remove the ascii letter at the begining of the data points yourself.

Which part of the code in processing that i should amend?

Thank you so much for your reply!

**Comment by biomurph** [comment]
@qkaifong 
Please use the Processing sketch here
https://github.com/WorldFamousElectronics/Pulse-Sensor-Processing-2-Sensors-Visualizer
it is designed to graph the data from two sensors.
The code is commented well, and you should be able to modify it for any purpose that you like.

**Comment by qkaifong** [comment]
I did actually used that code as my foundation, i will try to work my way through. And if there's any more doubt, i will post my question here again. 

Thank you so much for your help!

**Comment by biomurph** [comment]
@qkaifong 
That's great!
If you have any questions about that code, please post an issue on that repo to keep things tidy.
