### ISSUE TITLE
There are no sketches on the Processing app when I open it.

### ISSUE THREAD

**Issue by aimalabid** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#26]

**Comment by aimalabid** [comment]
Please make a tutorial for Mac. I am very confused.

**Comment by aimalabid** [comment]
Please, I opened processing but it says the sketchpad is empty?? @joelSensor help please

**Comment by aimalabid** [comment]
Problem Resolved!

**Comment by biomurph** [comment]
I'm happy you solved your problem!
Enjoy using your Pulse Sensor!
