### ISSUE TITLE
cannot run on Arduino 1.6.5

### ISSUE THREAD

**Issue by neoedmund** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#5]
import processing.serial.*;
~~~~~~~~ 'import' does not name a type

the source seems not compile in IDE, did I missed something?

Thank you.

**Comment by yahia0077** [comment]
import processing.serial.*;
~~~~~~~~ 'import' does not name a type

the source seems not compile in IDE, did I missed something?

Thank you.

**Comment by PetarMI** [comment]
You have to run it from the Processing IDE.

**Comment by biomurph** [comment]
download processing from www.processing.org

**Comment by shajjad3** [comment]
Hello! I am working with pulse sensor. The LED from pin no 13 is blinking according to the pulse. Its working.
But pulse sensor amped visualizer is nor working! It just shows a straight line and not gives BPM.
I used code from this site for both arduino and processing code. 
https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino
I am using Windows 7(32 bit), arduino IED 1.6.9
And processing 3.1.1 software.
I gave same baud rate to both arduino and processing code. 
Please suggest me how can I solve.
If possible please give the screenshot , how to fix it
Thanks
