### ISSUE TITLE
Link at readme does not work

### ISSUE THREAD

**Issue by MasaSip** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#6]
![screen shot 2015-12-01 at 10 48 39](https://cloud.githubusercontent.com/assets/2528591/11496222/2c0365c8-9819-11e5-9713-bc878a459e32.png)

the link refers to https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduinor
as it might be intended to https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino

**Comment by shajjad3** [comment]
Hello! I am working with pulse sensor. The LED from pin no 13 is blinking according to the pulse. Its working.
But pulse sensor amped visualizer is nor working! It just shows a straight line and not gives BPM.
I used code from this site for both arduino and processing code. 
https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino
I am using Windows 7(32 bit), arduino IED 1.6.9
And processing 3.1.1 software.
I gave same baud rate to both arduino and processing code. 
Please suggest me how can I solve.
If possible please give the screenshot , how to fix it
Thanks

**Comment by KiDooooo** [comment]
@shajjad3  i also have same problem..

**Comment by KiDooooo** [comment]
@joelSensor plz help

**Comment by joelSensor** [comment]
@KiDooooo 
This issue is about a previous version of the code.
Can you be more specific about what exactly the problem is?

**Comment by KiDooooo** [comment]
@joelSensor pulse sensor amped visualizer 1.5.0 is nor working! It just shows a straight line and not gives BPM.
I used code from this site for both arduino and processing code. I am using Windows 8.1(32 bit), arduino IED 1.6.7
And processing 3.2.1 software.
I gave same baud rate to both arduino and processing code.
Please suggest me how can I solve.

**Comment by joelSensor** [comment]
can you confirm that you programmed your arduino with the code found here
https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino
and that you changed the variable outputType to PROCESSING_VISUALIZER as shown in the READ ME?

Also, which serial port are you selecting? Make sure that you choose the right one.

**Comment by KiDooooo** [comment]
yes @joelSensor  i definately confirmed that i use same code ,also i changed the variable outputType to PROCESSING_VISUALIZER as shown in the READ ME. But still no effect
![heartlight-0783](https://cloud.githubusercontent.com/assets/26401521/23936502/938669da-0978-11e7-84d6-3fe9c6baa135.jpg)

**Comment by KiDooooo** [comment]
thank u so much for answering...!!! plz help

**Comment by KiDooooo** [comment]
is there any modification that is required ....!!!

**Comment by joelSensor** [comment]
There is no modification.
I feel that you are simply missing something simple. 
Make sure that you upload the code to the Arduino.
Make sure that you select the correct serial port in the visualizer, which is the same port you used to upload to the Arduino.

**Comment by shajjad3** [comment]
Thanks problem is solved.:-)

**Comment by joelSensor** [comment]
Please share the solution

**Comment by KiDooooo** [comment]
@shajjad3 tell me plz what is solution....!!!!
