### ISSUE TITLE
Processing 3.1.1 error with Arduino Leonardo

### ISSUE THREAD

**Issue by danielpetre** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#9]
Hi, so uploaded the Arduino Leonardo code to my r3 Leo and when running Processing with your code it says "Could not run the sketch" and breaks at:

  println(Serial.list());    // print a list of available serial ports

any ideas please?

**Comment by biomurph** [comment]
You may need to select the right serial port.
Please send the entire error message that processing gives you

**Comment by danielpetre** [comment]
got a Uno, the Leonardo was kindof faulty.
